[FIX] dashboard widget sorting ux (Podio bug_57)
pixelant/dashboard pull request #4
Opened 2017-02-20 01:24 UTC by yosokus

2017-02-20 07:15 UTC, MattiasNilsson commented
This looks good! There is just some minor things to tend to. 💯

2017-02-20 07:15 UTC, MattiasNilsson requested changes

2017-02-20 07:15 UTC, MattiasNilsson commented on Classes/ViewHelpers/Be/DashboardWidget/GridAttributesViewHelper.php
> +     * Returns grid item attributes
Add some more documentation about what actually take places in the code.

2017-02-20 07:15 UTC, MattiasNilsson commented on Classes/ViewHelpers/Be/DashboardWidget/GridAttributesViewHelper.php
> +        $attributes = 'class="' . $className . ' col-md-' . ($width * 4) . ' height-' . $height . '"' .
Use sprintf for easier reading here.

2017-02-20 07:15 UTC, MattiasNilsson commented on Classes/ViewHelpers/Be/DashboardWidget/GridAttributesViewHelper.php
> +            ' data-w="' . $width . '" data-h="' . $height. '"';
data-h => data-height
data-w => data-width

2017-02-20 07:15 UTC, MattiasNilsson commented on Classes/ViewHelpers/Be/DashboardWidget/GridAttributesViewHelper.php
> +    /**
Add comment

2017-02-20 07:15 UTC, MattiasNilsson commented on Classes/ViewHelpers/Be/DashboardWidget/GridAttributesViewHelper.php
> +     * @param int $width
integer

2017-02-20 07:15 UTC, MattiasNilsson commented on Classes/ViewHelpers/Be/DashboardWidget/GridAttributesViewHelper.php
> +     * @param int $numberOfCols
integer

2017-02-20 07:15 UTC, MattiasNilsson commented on Classes/ViewHelpers/Be/DashboardWidget/GridAttributesViewHelper.php
> +    /**
Add comment

2017-02-20 07:15 UTC, MattiasNilsson commented on Classes/ViewHelpers/Be/DashboardWidget/GridAttributesViewHelper.php
> +     * @param int $height
integer

2017-02-20 07:15 UTC, MattiasNilsson commented on Resources/Public/JavaScript/GridList.js
> +define(['jquery', 'draggableGridList', 'jquery-ui/draggable'], function ($) {
Add documentation about the file

2017-02-20 07:15 UTC, MattiasNilsson commented on Resources/Public/JavaScript/GridList.js
> +		console.log('GridList initialize END');
Remove console.log

2017-02-20 07:15 UTC, MattiasNilsson commented on Resources/Public/JavaScript/jquery.draggableGridList.js
> +// It does not try to register in a CommonJS environment since jQuery is not
Use proper docs:
/**
*/

2017-02-20 07:15 UTC, MattiasNilsson commented on Resources/Public/JavaScript/jquery.draggableGridList.js
> +			/**
This should go before the function

2017-02-20 07:15 UTC, MattiasNilsson commented on Resources/Public/JavaScript/jquery.draggableGridList.js
> +			/**
This should go before the method.

2017-02-20 10:27 UTC, yosokus commented
@MattiasNilsson. Please review and provide feedback.

2017-02-21 06:22 UTC, MattiasNilsson commented
Nice 💯

2017-02-21 06:22 UTC, MattiasNilsson approved these changes

2017-02-21 06:22 UTC, merged