[FIX] fix overlapping widgets (Podio_75)
pixelant/dashboard pull request #5
Opened 2017-02-21 07:14 UTC by yosokus

2017-02-21 07:15 UTC, yosokus commented
@MattiasNilsson please review my pull request

2017-02-21 11:18 UTC, MattiasNilsson requested changes

2017-02-21 11:18 UTC, MattiasNilsson commented on Resources/Public/JavaScript/GridList.js
> +		var grid = $(".gridster ul");
Use single quote instead of double.

2017-02-22 01:41 UTC, yosokus commented
@MattiasNilsson  please review my pull request.

2017-02-22 09:54 UTC, MattiasNilsson approved these changes

2017-02-22 09:54 UTC, merged