[FEATURE] dashboard tabs with iframes functionality (Podio feature_89)
pixelant/dashboard pull request #6
Opened 2017-02-21 10:39 UTC by yosokus

2017-02-21 11:19 UTC, MattiasNilsson commented
Looks good, just some minor things.

2017-02-21 11:19 UTC, MattiasNilsson requested changes

2017-02-21 11:19 UTC, MattiasNilsson commented on Classes/DashboardWidgets/IframeWidget.php
> +    const IDENTIFIER = 1487642496;
Identifier for what?

2017-02-21 11:19 UTC, MattiasNilsson commented on Classes/DashboardWidgets/IframeWidget.php
> +        $actionView->assign('url', $this->url);
replace usage of assign with assignMultiple

2017-02-22 01:17 UTC, yosokus commented on Configuration/TCA/DashboardWidgetSettings.php
> +$iframeWidgetId = \TYPO3\CMS\Dashboard\DashboardWidgets\IframeWidget::IDENTIFIER;
@MattiasNilsson the identifier is used here

2017-02-22 01:19 UTC, yosokus commented on ext_tables.php
> +        \TYPO3\CMS\Dashboard\DashboardWidgets\IframeWidget::IDENTIFIER => array(
@MattiasNilsson the identifier is also used here

2017-02-22 01:24 UTC, yosokus commented on Classes/DashboardWidgets/IframeWidget.php
> +    const IDENTIFIER = 1487642496;
@MattiasNilsson that the widget identifier. It is used in 2 files so I used a constant for easy retrieval.

2017-02-22 01:28 UTC, yosokus commented on Resources/Private/Templates/DashboardWidgets/IframeWidget.html
> +  <iframe class="iframe-widget" src="{url}" width="100%" height="100%" scrolling="{scrolling}"></iframe>
@MattiasNilsson  should I remove the scrolling option? I'm not sure it is needed.

2017-02-22 09:53 UTC, MattiasNilsson commented on Resources/Private/Templates/DashboardWidgets/IframeWidget.html
> +  <iframe class="iframe-widget" src="{url}" width="100%" height="100%" scrolling="{scrolling}"></iframe>
Keep it for now.

2017-02-22 09:53 UTC, MattiasNilsson approved these changes

2017-02-22 09:53 UTC, merged